# Generated by Django 5.2.12 on 2026-03-26 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist_Professional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oharmacist_diplome', models.ImageField(blank=True, null=True, upload_to='pharmacists/diplome/')),
                ('pharmacy_numero_ordre', models.CharField(blank=True, max_length=100)),
                ('pharmacy_autorisation_ouverture', models.ImageField(blank=True, null=True, upload_to='pharmacists/autorisation/')),
                ('pharmacy_numero_registre_commerce', models.CharField(blank=True, max_length=100)),
                ('pharmacy_convention_cnas', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=10)),
                ('pharmacist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='pharmacy.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('pharmacy_address', models.TextField(blank=True)),
                ('pharmacy_hours', models.CharField(blank=True, max_length=200)),
                ('pharmacy_license_number', models.CharField(blank=True, max_length=100)),
                ('pharmacy_location', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('pharmacist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='pharmacy.pharmacist')),
            ],
        ),
    ]
