# Generated by Django 5.2.12 on 2026-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
