# Generated by Django 5.2.12 on 2026-03-24 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_card_number', models.CharField(blank=True, max_length=50)),
                ('id_card_photo', models.ImageField(blank=True, null=True, upload_to='caretakers/id/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('wilaya', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker_professional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.ImageField(blank=True, null=True, upload_to='caretakers/diplome/')),
                ('certificat_formation', models.ImageField(blank=True, null=True, upload_to='caretakers/certificats/')),
                ('annees_experience', models.IntegerField(default=0)),
                ('references', models.TextField(blank=True)),
                ('casier_judiciaire', models.ImageField(blank=True, null=True, upload_to='caretakers/casier/')),
                ('caretaker_type', models.CharField(choices=[('professional', 'Professional'), ('family', 'Family Member')], default='professional', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('caretaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='caretaker.caretaker')),
            ],
        ),
    ]
