# Generated by Django 5.2.12 on 2026-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='address',
            new_name='caretaker_address',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='city',
            new_name='caretaker_city',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='date_of_birth',
            new_name='caretaker_date_of_birth',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='id_card_number',
            new_name='caretaker_id_card_number',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='id_card_photo',
            new_name='caretaker_id_card_photo',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='phone',
            new_name='caretaker_phone',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='postal_code',
            new_name='caretaker_postal_code',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='sex',
            new_name='caretaker_sex',
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='wilaya',
            new_name='caretaker_wilaya',
        ),
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='certificat_formation',
            new_name='caretaker_certificat_formation',
        ),
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='references',
            new_name='caretaker_references',
        ),
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='annees_experience',
            new_name='caretakerannees_experience',
        ),
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='diplome',
            new_name='caretakerdiplome',
        ),
        migrations.RemoveField(
            model_name='caretaker_professional_info',
            name='casier_judiciaire',
        ),
        migrations.AlterField(
            model_name='caretaker_professional_info',
            name='caretaker_type',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('infirmier', 'Infirmier'), ('aide-soignant', 'Aide_soignant'), ('auxiliare de vie', 'Auxiliare de vie'), ('paramedical', 'Paramedical'), ('family member', 'Family Member')], default='assistant', max_length=20),
        ),
    ]
