# Generated by Django 5.2.12 on 2026-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0002_rename_address_caretaker_caretaker_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='caretaker_phone',
            new_name='caretaker_phone_professionel',
        ),
    ]
