# Generated by Django 5.2.12 on 2026-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0003_rename_caretaker_phone_caretaker_caretaker_phone_professionel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_address',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_city',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_id_card_number',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_id_card_photo',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_phone_professionel',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_postal_code',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_sex',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretaker_wilaya',
        ),
    ]
