# Generated by Django 5.2.12 on 2026-03-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0004_remove_caretaker_caretaker_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='caretakerdiplome',
            new_name='caretaker_diplome',
        ),
        migrations.RenameField(
            model_name='caretaker_professional_info',
            old_name='caretakerannees_experience',
            new_name='caretaker_experience_years',
        ),
    ]
