# Generated by Django 5.2.12 on 2026-03-26 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_professionel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_professional_phone', models.CharField(blank=True, max_length=20)),
                ('doctor_diplome', models.ImageField(blank=True, null=True, upload_to='diplome_images/')),
                ('doctor_experience_years', models.IntegerField(blank=True, null=True)),
                ('doctor_medical_speciality', models.CharField(blank=True, max_length=255)),
                ('doctor_num_denregistration_au_conseil_de_ordre', models.CharField(blank=True, max_length=255)),
                ('doctor_license_number', models.CharField(blank=True, max_length=255)),
                ('doctor_authorisation_exercer', models.ImageField(blank=True, null=True, upload_to='autorisation_exercer_images/')),
                ('doctor_convention_cnas', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_professionel_info', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etablissement', models.CharField(choices=[('prive', 'Privé'), ('public', 'Public'), ('adomicile', 'Adomicile')], default='prive', max_length=10)),
                ('nom_etablissement', models.CharField(blank=True, max_length=255)),
                ('adresse_etablissement', models.CharField(blank=True, max_length=255)),
                ('doctor_exercer_hours', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='doctors.doctor')),
            ],
        ),
    ]
